- name: Configure Kubernetes Users
  become: true
  block:
    - name: Create k8s-configs directory
      file:
        path: ~/k8s-configs/
        state: directory
        mode: 0755

    - name: Copy student kubeconfig generation script
      copy:
        src: files/generate-user-k8s-config.sh
        dest: ~/k8s-configs/generate-user-k8s-config.sh
        mode: 0755

    - name: Applying k8s configurations for all
      become: true
      copy:
        src: "files/user-profile.sh"
        dest: "/etc/profile.d/k3s.sh"
        owner: root
        group: root
        mode: 0644

    - name: Setup Kubernetes Users' Configs
      include_tasks: user-config.yml
      loop: "{{ students }}"
      loop_control:
        loop_var: user

    - name: Setup Kubernetes Admins' Configs
      include_tasks: admin-config.yml
      loop: "{{ admins }}"
      loop_control:
        loop_var: user
