- name: Add Kubernetes GPG key
  become: true
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key

- name: Add Kubernetes APT repository
  become: true
  apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /
