---
- name: Install and configure JupyterHub
  hosts: localhost
  become: yes

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install system dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-dev
          - nodejs
          - npm
        state: present


    - name: Install JupyterHub and Python packages without --break-system-packages
      shell: |
        pip install jupyterhub jupyterlab notebook numpy matplotlib pandas
      args:
        executable: /bin/bash

    - name: Configuration Proxy
      shell: |
        npm install -g configurable-http-proxy
      args:
        executable: /bin/bash

    - name: Create JupyterHub installation directory
      file:
        path: /opt/jupyterhub
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy configuration files
      copy:
        src: "{{ item }}"
        dest: "/opt/jupyterhub/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - jupyterhub_config.py
        - iniciarJupyterHub.sh

    - name: Make iniciaJupyterHub.sh executable
      file:
        path: /opt/jupyterhub/iniciarJupyterHub.sh
        mode: '0755'

    - name: Start JupyterHub
      shell: /opt/jupyterhub/iniciarJupyterHub.sh
      async: 60
      poll: 0